common_base_packages_packages:
  - build-essential
  - htop
  - screen
  - tmux
  - vim
  - python-software-properties
  - wget
  - ntp
  - unzip
  - python-pip
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
