---
- name: Install stuff, configure sites & DB's
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common/timezone
    - common/base-packages
    - common/aws
    - common/docker
    - studioboz/main

- name: Configure P3K
  hosts: stage
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - studioboz/aws
    - studioboz/nginx
    - studioboz/p3k

- name: Configure DB
  hosts: db
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - studioboz/mysql
