- name: Change default nginx site
  template: src={{ nginx_host_template }} dest={{ nginx_host_file }}
  notify: restart nginx
  
- name: Ensure the default site is enabled
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
