---
  - name: AWS | Assures dir exists
    become: yes
    become_user: studioboz
    file: path="~/.aws" state=directory

  - name: AWS | create credentials
    become: yes
    become_user: studioboz
    template:
      src: aws_credentials.tpl
      dest: "~/.aws/credentials"

  - name: AWS | create config
    become: yes
    become_user: studioboz
    template:
      src: aws_config.tpl
      dest: "~/.aws/config"
