---
  - name: Docker | Add GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Docker | Add APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Docker | Install
    apt:     name=docker-ce